### ISSUE TITLE
 [QUESTION] Why use tanh instead of softmax to make classification ?

### ISSUE THREAD

**Issue by Scrooge20291224** [2vin/Siamese-MNIST#1]
I appreciate that your tutorial helps me understand the Siamese Network, but there is still a design that puzzles me, why use tanh in the base_network? in which case will it output negative values?

Thx !

**Comment by 2vin** [comment]
Hi, thanks for your question:
The reason why I used "tanh" is because I wanted to analyze my results keeping the base network same as Le-Net which was initial network on the DIGITS recognition task. You can play around with different networks that suit your needs.

**Comment by Scrooge20291224** [comment]
> Hi, thanks for your question:
> The reason why I used "tanh" is because I wanted to analyze my results keeping the base network same as Le-Net which was initial network on the DIGITS recognition task. You can play around with different networks that suit your needs.

It's very nice of you! thanks for your reply !
